### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'model.json'

### ISSUE THREAD

**Issue by johnfelipe** [OmdenaAI/omdena-pakistan-covid-analysis#6]
how can solve that?

**Comment by johnfelipe** [comment]
root@eh682214710:~/omdena-pakistan-covid-analysis/src/tasks/task5 deployment/covid detection by Fahad Ahmed# streamlit run app.py
	2022-01-11 00:05:34.508309: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
	2022-01-11 00:05:34.508353: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

	  You can now view your Streamlit app in your browser.

	  Network URL: http://10.1.0.4:8501
	  External URL: http://20.122.93.89:8501

	2022-01-11 00:05:36.277 Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/legacy_caching/caching.py", line 540, in get_or_create_cached_value
		return_value = _read_from_cache(
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/legacy_caching/caching.py", line 339, in _read_from_cache
		raise e
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/legacy_caching/caching.py", line 324, in _read_from_cache
		return _read_from_mem_cache(
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/legacy_caching/caching.py", line 242, in _read_from_mem_cache
		raise CacheKeyNotFoundError("Key not found in mem cache")
	streamlit.legacy_caching.caching.CacheKeyNotFoundError: Key not found in mem cache

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/script_runner.py", line 354, in _run_script
		exec(code, module.__dict__)
	  File "/root/omdena-pakistan-covid-analysis/src/tasks/task5 deployment/covid detection by Fahad Ahmed/app.py", line 25, in <module>
		model = load_model()
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/legacy_caching/caching.py", line 574, in wrapped_func
		return get_or_create_cached_value()
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/legacy_caching/caching.py", line 558, in get_or_create_cached_value
		return_value = func(*args, **kwargs)
	  File "/root/omdena-pakistan-covid-analysis/src/tasks/task5 deployment/covid detection by Fahad Ahmed/app.py", line 10, in load_model
		f = open('model.json', 'r')
	FileNotFoundError: [Errno 2] No such file or directory: 'model.json'

	2022-01-11 00:05:39.556 Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/legacy_caching/caching.py", line 540, in get_or_create_cached_value
		return_value = _read_from_cache(
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/legacy_caching/caching.py", line 339, in _read_from_cache
		raise e
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/legacy_caching/caching.py", line 324, in _read_from_cache
		return _read_from_mem_cache(
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/legacy_caching/caching.py", line 242, in _read_from_mem_cache
		raise CacheKeyNotFoundError("Key not found in mem cache")
	streamlit.legacy_caching.caching.CacheKeyNotFoundError: Key not found in mem cache

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/script_runner.py", line 354, in _run_script
		exec(code, module.__dict__)
	  File "/root/omdena-pakistan-covid-analysis/src/tasks/task5 deployment/covid detection by Fahad Ahmed/app.py", line 25, in <module>
		model = load_model()
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/legacy_caching/caching.py", line 574, in wrapped_func
		return get_or_create_cached_value()
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/legacy_caching/caching.py", line 558, in get_or_create_cached_value
		return_value = func(*args, **kwargs)
	  File "/root/omdena-pakistan-covid-analysis/src/tasks/task5 deployment/covid detection by Fahad Ahmed/app.py", line 10, in load_model
		f = open('model.json', 'r')
	FileNotFoundError: [Errno 2] No such file or directory: 'model.json'

still error pls help me to solve this ASAP
